apiVersion: v1
kind: ConfigMap
metadata:
  name: dingtalk-config
  namespace: public-service
data:
  config.yml: |-
    targets:
      webhook:
        url: #修改为钉钉机器人的webhook
        mention:
          all: true             #@所有人
